project:
  type: website
  output-dir: docs

website:
  title: "Mingya HUANG"
  navbar:
    search: true
    right:
      - href: about.qmd
        text: Home
      - href: publications.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - icon: github
        href: https://github.com/mhuang233

format:
  html:
    page-layout: full
    theme: 
      light: cosmo
      dark: slate
    css: styles.css
    toc: false
    mainfont: system-ui;
    fontsize: 1.2em
    linestretch: 1.7

editor: visual

