project:
  type: website
  output-dir: docs

website:
  title: "Mingya HUANG"
  navbar:
    right:
      - href: about.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: teaching.qmd
        text: Teaching

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

