project:
  type: website
  output-dir: docs

website:
  title: "Mingya HUANG"
  navbar:
    search: true
    right:
      - href: about.qmd
        text: About
      - href: CV_MH.pdf
        text: Vitae
      - href: publications.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      #- icon: github
      #  href: https://github.com/mhuang233
  page-footer:
    center: "Copyright © 2025 M Huang"
    border: false

format:
  html:
    theme: 
      light: cosmo
      dark: slate
    css: styles.css
    toc: false
    mainfont: system-ui;
    fontsize: 1.2em
    linestretch: 1.7

editor: visual